development: &default
  adapter: postgresql
  encoding: unicode
  database: industry_development
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME', 'industry') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'industry') %>
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>
 
test: &test
  <<: *default
  database: industry_test
