development: &default
  adapter: postgresql
  encoding: unicode
  database: industry_development
  pool: 5
  username: postgres
  password: 
  host: db
 
test: &test
  <<: *default
  database: industry_test
